// AUTOGENERATED FILE BY CODE GENERATOR. DO NOT EDIT.
// Source: generator.yaml
package risken

import (
	"context"

	proto "github.com/ca-risken/core/proto/organization"
)

func (c *Client) ListOrganization(ctx context.Context, req *proto.ListOrganizationRequest) (*proto.ListOrganizationResponse, error) {
	httpReq, err := c.NewRequest(ctx, "GET", "/api/v1/organization/list-organization", req)
	if err != nil {
		return nil, err
	}
	httpResp, err := c.Do(httpReq)
	if err != nil {
		return nil, err
	}
	var resp proto.ListOrganizationResponse
	if err := decodeBodyWithDataKey(httpResp, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
