// AUTOGENERATED FILE BY CODE GENERATOR. DO NOT EDIT.
// Source: generator.yaml
package risken

import (
	"context"

	proto "github.com/ca-risken/core/proto/report"
)

func (c *Client) GetReportFinding(ctx context.Context, req *proto.GetReportFindingRequest) (*proto.GetReportFindingResponse, error) {
	httpReq, err := c.NewRequest(ctx, "GET", "/api/v1/report/get-report", req)
	if err != nil {
		return nil, err
	}
	httpResp, err := c.Do(httpReq)
	if err != nil {
		return nil, err
	}
	var resp proto.GetReportFindingResponse
	if err := decodeBodyWithDataKey(httpResp, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
